export default {
    SUCCESS: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVICE_ERROR: 500,
    ADD_TO_PURCHASE: "ADD_TO_PURCHASE",
    CLEAR: "CLEAR",
};
